# -*- coding: utf-8 -*-
"""Wav2Vec2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-XxgY0_Fa9Z-_rv72vA6-7hCWmEBAMi
"""

!pip install transformers
!pip install datasets
!pip install evaluate
!pip install librosa
!pip install soundfile
!pip install accelerate
!pip install torchaudio

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

import os
import torch
import librosa
import numpy as np
import pandas as pd

from tqdm import tqdm

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

from transformers import (
    AutoProcessor,
    AutoModelForAudioClassification
)

from sklearn.metrics import (
    accuracy_score,
    f1_score
)

device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

print(device)

emotion_map = {
    "01":0,
    "02":1,
    "03":2,
    "04":3,
    "05":4,
    "06":5,
    "07":6,
    "08":7
}

emotion_names = {
    0:"neutral",
    1:"calm",
    2:"happy",
    3:"sad",
    4:"angry",
    5:"fearful",
    6:"disgust",
    7:"surprised"
}

import zipfile

zip_path = "/content/Audio_Speech_Actors_01-24.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/RAVDESS")

import os
import pandas as pd

emotion_map = {
    "01":0,
    "02":1,
    "03":2,
    "04":3,
    "05":4,
    "06":5,
    "07":6,
    "08":7
}

ROOT = "/content/RAVDESS"

rows = []

for actor in os.listdir(ROOT):

    actor_path = os.path.join(ROOT, actor)

    if not os.path.isdir(actor_path):
        continue

    actor_id = int(actor.split("_")[1])

    for file in os.listdir(actor_path):

        if not file.endswith(".wav"):
            continue

        emotion_code = file.split("-")[2]

        rows.append({
            "path": os.path.join(actor_path,file),
            "actor": actor_id,
            "label": emotion_map[emotion_code]
        })

df = pd.DataFrame(rows)

print(df.head())
print(len(df))

train_df = df[df.actor <= 20]

val_df = df[df.actor > 20]

print(len(train_df))
print(len(val_df))

from transformers import Wav2Vec2FeatureExtractor

feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(
    "facebook/wav2vec2-base"
)

from transformers import Wav2Vec2ForSequenceClassification

model = Wav2Vec2ForSequenceClassification.from_pretrained(
    "facebook/wav2vec2-base",
    num_labels=8,
    ignore_mismatched_sizes=True
)

class RAVDESSDataset(Dataset):

    def __init__(self, dataframe):

        self.df = dataframe.reset_index(drop=True)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        audio, sr = librosa.load(
            row.path,
            sr=16000
        )

        inputs = feature_extractor(
            audio,
            sampling_rate=16000,
            return_tensors="pt"
        )

        return {
            "input_values":
                inputs.input_values.squeeze(0),

            "label":
                torch.tensor(
                    row.label,
                    dtype=torch.long
                ),

            "path":
                row.path
        }

def collate_fn(batch):

    audio = [
        x["input_values"]
        for x in batch
    ]

    labels = torch.stack(
        [x["label"] for x in batch]
    )

    paths = [
        x["path"] for x in batch
    ]

    padded = torch.nn.utils.rnn.pad_sequence(
        audio,
        batch_first=True
    )

    return {
        "input_values": padded,
        "labels": labels,
        "paths": paths
    }

train_dataset = RAVDESSDataset(
    train_df
)

val_dataset = RAVDESSDataset(
    val_df
)

train_loader = DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True,
    collate_fn=collate_fn
)

val_loader = DataLoader(
    val_dataset,
    batch_size=8,
    shuffle=False,
    collate_fn=collate_fn
)

model = AutoModelForAudioClassification.from_pretrained(
    "superb/wav2vec2-base-superb-er",
    num_labels=8,
    ignore_mismatched_sizes=True
)

model.to(device)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-5
)

EPOCHS = 5

for epoch in range(EPOCHS):

    model.train()

    losses = []

    for batch in tqdm(train_loader):

        optimizer.zero_grad()

        input_values = batch["input_values"].to(device)

        labels = batch["labels"].to(device)

        outputs = model(
            input_values=input_values,
            labels=labels
        )

        loss = outputs.loss

        loss.backward()

        optimizer.step()

        losses.append(
            loss.item()
        )

    print(
        f"Epoch {epoch+1}"
    )

    print(
        np.mean(losses)
    )

model.eval()

preds = []
truths = []

with torch.no_grad():

    for batch in val_loader:

        input_values = batch[
            "input_values"
        ].to(device)

        labels = batch[
            "labels"
        ]

        logits = model(
            input_values=input_values
        ).logits

        predictions = torch.argmax(
            logits,
            dim=1
        )

        preds.extend(
            predictions.cpu().numpy()
        )

        truths.extend(
            labels.numpy()
        )

print(
    accuracy_score(
        truths,
        preds
    )
)

print(
    f1_score(
        truths,
        preds,
        average="weighted"
    )
)

SAVE_DIR = "/content/drive/MyDrive/models/wav2vec2_ravdess"

model.save_pretrained(
    SAVE_DIR
)

feature_extractor.save_pretrained(
    SAVE_DIR
)

softmax = torch.nn.Softmax(
    dim=1
)

features = []

model.eval()

for idx,row in tqdm(
    df.iterrows(),
    total=len(df)
):

    audio, sr = librosa.load(
        row.path,
        sr=16000
    )

    inputs = feature_extractor(
        audio,
        sampling_rate=16000,
        return_tensors="pt"
    )

    input_values = inputs.input_values.to(
        device
    )

    with torch.no_grad():

        wav_out = model.wav2vec2(
            input_values
        )

        embedding = (
            wav_out
            .last_hidden_state
            .mean(dim=1)
            .squeeze()
            .cpu()
            .numpy()
        )

        logits = model(
            input_values=input_values
        ).logits

        probs = softmax(
            logits
        ).squeeze()

    probs_np = probs.cpu().numpy()

    confidence = probs_np.max()

    fearful = probs_np[5]

    angry = probs_np[4]

    sad = probs_np[3]

    stress_score = (
        fearful
        + 0.8*angry
        + 0.4*sad
    )

    feature = {

        "path":
            row.path,

        "label":
            row.label,

        "stress_score":
            float(stress_score),

        "confidence":
            float(confidence)
    }

    for i,p in enumerate(
        probs_np
    ):

        feature[
            f"emotion_{i}"
        ] = float(p)

    for i,e in enumerate(
        embedding
    ):

        feature[
            f"emb_{i}"
        ] = float(e)

    features.append(
        feature
    )

features_df = pd.DataFrame(
    features
)

features_df.to_csv(
    "/content/drive/MyDrive/ScamDetection/features/audio_features.csv",
    index=False
)

print(
    features_df.shape
)

!pip install matplotlib

import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(
    truths,
    preds
)

display = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Neutral",
        "Calm",
        "Happy",
        "Sad",
        "Angry",
        "Fearful",
        "Disgust",
        "Surprised"
    ]
)

fig, ax = plt.subplots(figsize=(8,8))

display.plot(
    ax=ax,
    xticks_rotation=45,
    cmap="Blues",
    colorbar=False
)

plt.title("Emotion Confusion Matrix")
plt.show()

from sklearn.metrics import classification_report

print(
    classification_report(
        truths,
        preds,
        target_names=[
            "Neutral",
            "Calm",
            "Happy",
            "Sad",
            "Angry",
            "Fearful",
            "Disgust",
            "Surprised"
        ]
    )
)

import matplotlib.pyplot as plt

labels = train_df["label"].value_counts().sort_index()

plt.figure(figsize=(8,4))

plt.bar(
    emotion_names.values(),
    labels.values
)

plt.xticks(rotation=45)

plt.title("Training Samples per Emotion")

plt.show()

import numpy as np

cm = confusion_matrix(truths,preds)

per_class_accuracy = cm.diagonal()/cm.sum(axis=1)

for i,a in enumerate(per_class_accuracy):

    print(
        emotion_names[i],
        round(a,3)
    )

plt.figure(figsize=(7,4))

plt.hist(
    features_df["confidence"],
    bins=20
)

plt.title("Prediction Confidence")

plt.xlabel("Confidence")

plt.ylabel("Number of Samples")

plt.show()

plt.figure(figsize=(7,4))

plt.hist(
    features_df["stress_score"],
    bins=20
)

plt.title("Stress Score Distribution")

plt.xlabel("Stress Score")

plt.show()

wrong_predictions = []

model.eval()

with torch.no_grad():

    for batch in val_loader:

        logits = model(
            input_values=batch["input_values"].to(device)
        ).logits

        pred = torch.argmax(
            logits,
            dim=1
        ).cpu()

        labels = batch["labels"]

        paths = batch["paths"]   # make sure your collate_fn returns paths

        for p,t,path in zip(pred,labels,paths):

            if p != t:

                wrong_predictions.append({
                    "file":path,
                    "true":emotion_names[t.item()],
                    "pred":emotion_names[p.item()]
                })

import pandas as pd

wrong_df = pd.DataFrame(
    wrong_predictions
)

wrong_df.head(20)